---
title: "EEG analysis"
output: html_notebook
---

imports
```{r}
library(tidyr)
library(ggplot2)
library(RColorBrewer)
library(reshape2)
```

load data
```{r}
inexp_meditation_files = sort(list.files("ffted/",pattern="^0_ffted_med"))
inexp_reference_files = sort(list.files("ffted/",pattern="^0_ffted_ref"))
exp_meditation_files = sort(list.files("ffted/",pattern="^1_ffted_med"))
exp_reference_files = sort(list.files("ffted/",pattern="^1_ffted_ref"))


exp_meditation = list()
for(i in 1:length(exp_meditation_files)) {
  file = exp_meditation_files[i]
  exp_meditation[[i]] <-  read.csv(paste("ffted/", file, sep=""))
}

inexp_meditation = list()
for(i in 1:length(inexp_meditation_files)) {
  file = inexp_meditation_files[i]
  inexp_meditation[[i]] <-  read.csv(paste("ffted/", file, sep=""))
}

exp_reference = list()
for(i in 1:length(exp_reference_files)) {
  file = exp_reference_files[i]
  exp_reference[[i]] <-  read.csv(paste("ffted/", file, sep=""))
}

inexp_reference = list()
for(i in 1:length(inexp_reference_files)) {
  file = inexp_reference_files[i]
  inexp_reference[[i]] <-  read.csv(paste("ffted/", file, sep=""))
}
```


subsetting data
```{r}
#df <- data.frame(time = exp_meditation[[1]]$timestamps,
#                 alpha_1 = exp_meditation[[1]]$alpha_absolute_1,
#                 alpha_2 = exp_meditation[[1]]$alpha_absolute_2)
                 
                
#df <- melt(df, id.vars = 'time', variable.name = 'waves')
#ggplot(df, aes(time,value)) + geom_line(aes(colour = waves))

myfunction <- function(med, exp, wave, electrodes){
  browser()
  if(med){
    if(exp){
      df <- exp_meditation
    }
    else{
      df <- inexp_meditation
    }
  }
  else{
    if(exp){
      df <- exp_reference
    }
    else{
      df <- inexp_reference
    }
  }

  data = list()
  for(i in 1:length(df)) {
  data[[i]] <- df[[i]][, grepl(paste('(', wave, ')|(', electrodes, ')|(timestamp)', sep = ""), names(df[[i]]))]
  }
  return(data)
}
```


